'use strict';

Object.defineProperty(exports, "__esModule", {
  value: true
});

var _branding = require('../_utils/branding');

var separatorHeight = '16px';
var intValue = function intValue(value) {
  return parseInt(value, 10);
};

var _defaultExport = new String('.kirk-itemChoice{position:relative;display:-webkit-box;display:-webkit-flex;display:-ms-flexbox;display:flex;padding:0;padding-top:' + _branding.space.l + ';padding-bottom:' + _branding.space.l + ';-webkit-align-items:center;-webkit-box-align:center;-ms-flex-align:center;align-items:center;-webkit-flex:1;-ms-flex:1;flex:1;border:0;background:none;color:' + _branding.color.primaryText + ';font-size:' + _branding.font.m.size + ';line-height:' + _branding.font.m.lineHeight + ';-webkit-text-decoration:none;text-decoration:none;cursor:pointer;-webkit-user-select:none;-moz-user-select:none;-ms-user-select:none;user-select:none;-webkit-tap-highlight-color:' + _branding.color.tapHighlight + ';-webkit-touch-callout:none;width:100%;font-family:inherit;}.kirk-itemChoice--withSubLabel{padding-top:' + _branding.space.m + ';padding-bottom:' + _branding.space.m + ';}.kirk-itemChoice[aria-selected="true"]{background-color:' + _branding.color.lightBackground + ';}.kirk-itemChoice + .kirk-itemChoice{margin-top:' + separatorHeight + ';}.kirk-itemChoice + .kirk-itemChoice::before{content :\'\';position:absolute;top:-' + intValue(separatorHeight) / 2 + 'px;right:0;left:0;border-bottom:1px solid ' + _branding.color.border + ';}.kirk-chevron{margin-left:auto;}.kirk-itemChoice > span:first-of-type{margin-right:auto;}.kirk-itemChoice-label{color:' + _branding.color.primaryText + ';font-size:' + _branding.font.m.size + ';line-height:' + _branding.font.m.lineHeight + ';}.kirk-itemChoice--highlighted .kirk-itemChoice-label{color:' + _branding.color.primary + ';font-size:' + _branding.font.l.size + ';line-height:' + _branding.font.l.lineHeight + ';}.kirk-itemChoice-subLabel{color:' + _branding.color.secondaryText + ';font-size:' + _branding.font.base.size + ';line-height:' + _branding.font.base.lineHeight + ';margin-top:' + _branding.space.s + ';}.kirk-itemChoice-leftAddon{display:-webkit-inline-box;display:-webkit-inline-flex;display:-ms-inline-flexbox;display:inline-flex;-webkit-align-items:center;-webkit-box-align:center;-ms-flex-align:center;align-items:center;margin-right:' + _branding.space.l + ';}.kirk-itemChoice-rightAddon{display:-webkit-inline-box;display:-webkit-inline-flex;display:-ms-inline-flexbox;display:inline-flex;-webkit-align-items:center;-webkit-box-align:center;-ms-flex-align:center;align-items:center;margin-left:auto;}.kirk-itemChoice .kirk-icon{margin-left:auto;}.kirk-itemChoice .kirk-icon + .kirk-icon,.kirk-itemChoice-rightAddon + .kirk-icon{margin-left:' + _branding.space.m + ';}.kirk-button.kirk-itemChoice-checkmark{padding:0;margin-left:auto;min-height:24px;min-width:24px;}');

_defaultExport.__hash = '2950804917';
_defaultExport.__scoped = '.kirk-itemChoice{position:relative;display:-webkit-box;display:-webkit-flex;display:-ms-flexbox;display:flex;padding:0;padding-top:' + _branding.space.l + ';padding-bottom:' + _branding.space.l + ';-webkit-align-items:center;-webkit-box-align:center;-ms-flex-align:center;align-items:center;-webkit-flex:1;-ms-flex:1;flex:1;border:0;background:none;color:' + _branding.color.primaryText + ';font-size:' + _branding.font.m.size + ';line-height:' + _branding.font.m.lineHeight + ';-webkit-text-decoration:none;text-decoration:none;cursor:pointer;-webkit-user-select:none;-moz-user-select:none;-ms-user-select:none;user-select:none;-webkit-tap-highlight-color:' + _branding.color.tapHighlight + ';-webkit-touch-callout:none;width:100%;font-family:inherit;}.kirk-itemChoice--withSubLabel{padding-top:' + _branding.space.m + ';padding-bottom:' + _branding.space.m + ';}.kirk-itemChoice[aria-selected="true"]{background-color:' + _branding.color.lightBackground + ';}.kirk-itemChoice + .kirk-itemChoice{margin-top:' + separatorHeight + ';}.kirk-itemChoice + .kirk-itemChoice::before{content :\'\';position:absolute;top:-' + intValue(separatorHeight) / 2 + 'px;right:0;left:0;border-bottom:1px solid ' + _branding.color.border + ';}.kirk-chevron{margin-left:auto;}.kirk-itemChoice > span:first-of-type{margin-right:auto;}.kirk-itemChoice-label{color:' + _branding.color.primaryText + ';font-size:' + _branding.font.m.size + ';line-height:' + _branding.font.m.lineHeight + ';}.kirk-itemChoice--highlighted .kirk-itemChoice-label{color:' + _branding.color.primary + ';font-size:' + _branding.font.l.size + ';line-height:' + _branding.font.l.lineHeight + ';}.kirk-itemChoice-subLabel{color:' + _branding.color.secondaryText + ';font-size:' + _branding.font.base.size + ';line-height:' + _branding.font.base.lineHeight + ';margin-top:' + _branding.space.s + ';}.kirk-itemChoice-leftAddon{display:-webkit-inline-box;display:-webkit-inline-flex;display:-ms-inline-flexbox;display:inline-flex;-webkit-align-items:center;-webkit-box-align:center;-ms-flex-align:center;align-items:center;margin-right:' + _branding.space.l + ';}.kirk-itemChoice-rightAddon{display:-webkit-inline-box;display:-webkit-inline-flex;display:-ms-inline-flexbox;display:inline-flex;-webkit-align-items:center;-webkit-box-align:center;-ms-flex-align:center;align-items:center;margin-left:auto;}.kirk-itemChoice .kirk-icon{margin-left:auto;}.kirk-itemChoice .kirk-icon + .kirk-icon,.kirk-itemChoice-rightAddon + .kirk-icon{margin-left:' + _branding.space.m + ';}.kirk-button.kirk-itemChoice-checkmark{padding:0;margin-left:auto;min-height:24px;min-width:24px;}';
_defaultExport.__scopedHash = '2545686772';
exports.default = _defaultExport;
//# sourceMappingURL=style.js.map