'use strict';

Object.defineProperty(exports, "__esModule", {
  value: true
});

var _branding = require('../_utils/branding');

var _defaultExport = new String('.kirk-pushInfo{display:-webkit-box;display:-webkit-flex;display:-ms-flexbox;display:flex;-webkit-align-items:center;-webkit-box-align:center;-ms-flex-align:center;align-items:center;background:' + _branding.color.pushBackground + ';color:' + _branding.color.white + ';border-radius:' + _branding.radius.l + ';font-size:' + _branding.font.base.size + ';line-height:' + _branding.font.base.lineHeight + ';font-weight:' + _branding.fontWeight.regular + ';padding:0 ' + _branding.space.l + ';max-height:0;overflow-y:hidden;-webkit-animation:slide-down 700ms ease-out 300ms forwards;animation:slide-down 700ms ease-out 300ms forwards;}@-webkit-keyframes slide-down{0%{max-height:0;}100%{max-height:300px;padding-top:' + _branding.space.l + ';padding-bottom:' + _branding.space.l + ';}}@keyframes slide-down{0%{max-height:0;}100%{max-height:300px;padding-top:' + _branding.space.l + ';padding-bottom:' + _branding.space.l + ';}}.kirk-pushInfo-headline{font-size:' + _branding.font.m.size + ';line-height:' + _branding.font.m.lineHeight + ';font-weight:' + _branding.fontWeight.medium + ';margin:0 0 ' + _branding.space.m + ';}.kirk-pushInfo-headline--standalone{margin:0;}.kirk-pushInfo-content{margin:0;}.kirk-pushInfo-icon{display:-webkit-inline-box;display:-webkit-inline-flex;display:-ms-inline-flexbox;display:inline-flex;-webkit-align-items:center;-webkit-box-align:center;-ms-flex-align:center;align-items:center;-webkit-box-pack:center;-webkit-justify-content:center;-ms-flex-pack:center;justify-content:center;border-radius:50%;min-width:40px;min-height:40px;margin-right:' + _branding.space.l + ';background-color:' + _branding.color.white + ';}');

_defaultExport.__hash = '3274796727';
_defaultExport.__scoped = '.kirk-pushInfo.jsx-1594299766{display:-webkit-box;display:-webkit-flex;display:-ms-flexbox;display:flex;-webkit-align-items:center;-webkit-box-align:center;-ms-flex-align:center;align-items:center;background:' + _branding.color.pushBackground + ';color:' + _branding.color.white + ';border-radius:' + _branding.radius.l + ';font-size:' + _branding.font.base.size + ';line-height:' + _branding.font.base.lineHeight + ';font-weight:' + _branding.fontWeight.regular + ';padding:0 ' + _branding.space.l + ';max-height:0;overflow-y:hidden;-webkit-animation:slide-down-jsx-1594299766 700ms ease-out 300ms forwards;animation:slide-down-jsx-1594299766 700ms ease-out 300ms forwards;}@-webkit-keyframes slide-down-jsx-1594299766{0%{max-height:0;}100%{max-height:300px;padding-top:' + _branding.space.l + ';padding-bottom:' + _branding.space.l + ';}}@keyframes slide-down-jsx-1594299766{0%{max-height:0;}100%{max-height:300px;padding-top:' + _branding.space.l + ';padding-bottom:' + _branding.space.l + ';}}.kirk-pushInfo-headline.jsx-1594299766{font-size:' + _branding.font.m.size + ';line-height:' + _branding.font.m.lineHeight + ';font-weight:' + _branding.fontWeight.medium + ';margin:0 0 ' + _branding.space.m + ';}.kirk-pushInfo-headline--standalone.jsx-1594299766{margin:0;}.kirk-pushInfo-content.jsx-1594299766{margin:0;}.kirk-pushInfo-icon.jsx-1594299766{display:-webkit-inline-box;display:-webkit-inline-flex;display:-ms-inline-flexbox;display:inline-flex;-webkit-align-items:center;-webkit-box-align:center;-ms-flex-align:center;align-items:center;-webkit-box-pack:center;-webkit-justify-content:center;-ms-flex-pack:center;justify-content:center;border-radius:50%;min-width:40px;min-height:40px;margin-right:' + _branding.space.l + ';background-color:' + _branding.color.white + ';}';
_defaultExport.__scopedHash = '1594299766';
exports.default = _defaultExport;
//# sourceMappingURL=style.js.map