'use strict';

Object.defineProperty(exports, "__esModule", {
  value: true
});

var _branding = require('../_utils/branding');

var _defaultExport = new String('.drawer{position:absolute;top:0;left:0;bottom:0;right:0;}.drawer::after{content:\'\';position:absolute;top:0;left:0;bottom:0;right:0;z-index:1;background-color:rgba(0,0,0,0);-webkit-transition:background-color 150ms linear;transition:background-color 150ms linear;}.drawer--open::after{background-color:rgba(0,0,0,.3);}.drawer--close::after{background-color:rgba(0,0,0,0);}.scrollableContent{position:absolute;z-index:1050;top:0;left:0;bottom:0;overflow-y:auto;background-color:' + _branding.color.white + ';box-shadow:0 36px 36px 0 rgba(0,0,0,.3);-webkit-transition:-webkit-transform ' + _branding.transition.duration.base + ' ease-in-out;-webkit-transition:transform ' + _branding.transition.duration.base + ' ease-in-out;transition:transform ' + _branding.transition.duration.base + ' ease-in-out;will-change:transform;-webkit-transform:translateX(-100%);-ms-transform:translateX(-100%);transform:translateX(-100%);max-width:100%;-webkit-overflow-scrolling:touch;}.drawer--open .scrollableContent{-webkit-transform:translateX(0%);-ms-transform:translateX(0%);transform:translateX(0%);}.drawer--close .scrollableContent{-webkit-transform:translateX(-100%);-ms-transform:translateX(-100%);transform:translateX(-100%);}');

_defaultExport.__hash = '4011658332';
_defaultExport.__scoped = '.drawer.jsx-1397227485{position:absolute;top:0;left:0;bottom:0;right:0;}.drawer.jsx-1397227485::after{content:\'\';position:absolute;top:0;left:0;bottom:0;right:0;z-index:1;background-color:rgba(0,0,0,0);-webkit-transition:background-color 150ms linear;transition:background-color 150ms linear;}.drawer--open.jsx-1397227485::after{background-color:rgba(0,0,0,.3);}.drawer--close.jsx-1397227485::after{background-color:rgba(0,0,0,0);}.scrollableContent.jsx-1397227485{position:absolute;z-index:1050;top:0;left:0;bottom:0;overflow-y:auto;background-color:' + _branding.color.white + ';box-shadow:0 36px 36px 0 rgba(0,0,0,.3);-webkit-transition:-webkit-transform ' + _branding.transition.duration.base + ' ease-in-out;-webkit-transition:transform ' + _branding.transition.duration.base + ' ease-in-out;transition:transform ' + _branding.transition.duration.base + ' ease-in-out;will-change:transform;-webkit-transform:translateX(-100%);-ms-transform:translateX(-100%);transform:translateX(-100%);max-width:100%;-webkit-overflow-scrolling:touch;}.drawer--open.jsx-1397227485 .scrollableContent.jsx-1397227485{-webkit-transform:translateX(0%);-ms-transform:translateX(0%);transform:translateX(0%);}.drawer--close.jsx-1397227485 .scrollableContent.jsx-1397227485{-webkit-transform:translateX(-100%);-ms-transform:translateX(-100%);transform:translateX(-100%);}';
_defaultExport.__scopedHash = '1397227485';
exports.default = _defaultExport;
//# sourceMappingURL=style.js.map