'use strict';

Object.defineProperty(exports, "__esModule", {
  value: true
});

var _branding = require('../_utils/branding');

var _defaultExport = new String('.dropdownButton{position:relative;display:inline-block;}.dropdownButton>button{display:-webkit-box;display:-webkit-flex;display:-ms-flexbox;display:flex;-webkit-box-pack:justify;-webkit-justify-content:space-between;-ms-flex-pack:justify;justify-content:space-between;-webkit-align-items:center;-webkit-box-align:center;-ms-flex-align:center;align-items:center;color:' + _branding.color.primary + ';background:none;border:0;outline:0;font-size:' + _branding.font.base.size + ';cursor:pointer;}.dropdownButton .kirk-icon{-webkit-transition:-webkit-transform ' + _branding.transition.duration.base + ' ease-out;-webkit-transition:transform ' + _branding.transition.duration.base + ' ease-out;transition:transform ' + _branding.transition.duration.base + ' ease-out;}.dropdownButton[open] .kirk-icon{-webkit-transform:rotate(180deg);-ms-transform:rotate(180deg);transform:rotate(180deg);}.dropdown{position:absolute;top:100%;box-shadow:0 16px 32px 0 rgba(0,0,0,.3);width:350px;}.dropdown--left{left:0;}.dropdown--right{right:0;}.dropdown--withPointer{margin-top:' + _branding.space.l + ';}.dropdown--withPointer::before{content:\'\';position:absolute;top:-10px;display:block;width:0;height:0;border-left:10px solid transparent;border-right:10px solid transparent;border-bottom:10px solid ' + _branding.color.white + ';}.dropdown--left::before{left:24px;}.dropdown--right::before{right:24px;}');

_defaultExport.__hash = '272305844';
_defaultExport.__scoped = '.dropdownButton.jsx-193583861{position:relative;display:inline-block;}.dropdownButton.jsx-193583861>button.jsx-193583861{display:-webkit-box;display:-webkit-flex;display:-ms-flexbox;display:flex;-webkit-box-pack:justify;-webkit-justify-content:space-between;-ms-flex-pack:justify;justify-content:space-between;-webkit-align-items:center;-webkit-box-align:center;-ms-flex-align:center;align-items:center;color:' + _branding.color.primary + ';background:none;border:0;outline:0;font-size:' + _branding.font.base.size + ';cursor:pointer;}.dropdownButton .kirk-icon{-webkit-transition:-webkit-transform ' + _branding.transition.duration.base + ' ease-out;-webkit-transition:transform ' + _branding.transition.duration.base + ' ease-out;transition:transform ' + _branding.transition.duration.base + ' ease-out;}.dropdownButton[open] .kirk-icon{-webkit-transform:rotate(180deg);-ms-transform:rotate(180deg);transform:rotate(180deg);}.dropdown.jsx-193583861{position:absolute;top:100%;box-shadow:0 16px 32px 0 rgba(0,0,0,.3);width:350px;}.dropdown--left.jsx-193583861{left:0;}.dropdown--right.jsx-193583861{right:0;}.dropdown--withPointer.jsx-193583861{margin-top:' + _branding.space.l + ';}.dropdown--withPointer.jsx-193583861::before{content:\'\';position:absolute;top:-10px;display:block;width:0;height:0;border-left:10px solid transparent;border-right:10px solid transparent;border-bottom:10px solid ' + _branding.color.white + ';}.dropdown--left.jsx-193583861::before{left:24px;}.dropdown--right.jsx-193583861::before{right:24px;}';
_defaultExport.__scopedHash = '193583861';
exports.default = _defaultExport;
//# sourceMappingURL=style.js.map