'use strict';

Object.defineProperty(exports, "__esModule", {
  value: true
});

var _branding = require('../_utils/branding');

var _defaultExport = new String('li{border:1px solid ' + _branding.color.border + ';border-radius:' + _branding.radius.l + ';list-style-type:none;}.kirk-tripCard a{display:block;padding:' + _branding.space.l + ';-webkit-text-decoration:none;text-decoration:none;}.kirk-tripCard-main{display:-webkit-box;display:-webkit-flex;display:-ms-flexbox;display:flex;margin-bottom:' + _branding.space.l + ';}.kirk-tripCard .kirk-tripCard-itinerary{-webkit-flex:1;-ms-flex:1;flex:1;}.kirk-tripCard-price{color:' + _branding.color.primaryText + ';font-size:' + _branding.font.m.size + ';line-height:' + _branding.font.m.lineHeight + ';font-weight:' + _branding.fontWeight.medium + ';}.kirk-tripCard--highlighted .kirk-tripCard-price{color:' + _branding.color.success + ';}.kirk-tripCard-bottom{display:-webkit-box;display:-webkit-flex;display:-ms-flexbox;display:flex;-webkit-align-items:center;-webkit-box-align:center;-ms-flex-align:center;align-items:center;}.kirk-tripCard-driver{display:-webkit-box;display:-webkit-flex;display:-ms-flexbox;display:flex;-webkit-align-items:center;-webkit-box-align:center;-ms-flex-align:center;align-items:center;-webkit-flex:1;-ms-flex:1;flex:1;color:' + _branding.color.primaryText + ';font-size:' + _branding.font.m.size + ';line-height:' + _branding.font.m.lineHeight + ';}.kirk-tripCard .kirk-tripCard-driver > div{margin-right:calc(' + _branding.space.xl + ' + 6px);}.kirk-tripCard .kirk-tripCard-flags svg{display:inline-block;margin-left:' + _branding.space.m + ';}.kirk-tripCard-topText{color:' + _branding.color.success + ';font-weight:' + _branding.fontWeight.medium + ';}');

_defaultExport.__hash = '1638116382';
_defaultExport.__scoped = 'li.jsx-2639181855{border:1px solid ' + _branding.color.border + ';border-radius:' + _branding.radius.l + ';list-style-type:none;}.kirk-tripCard.jsx-2639181855 a{display:block;padding:' + _branding.space.l + ';-webkit-text-decoration:none;text-decoration:none;}.kirk-tripCard-main.jsx-2639181855{display:-webkit-box;display:-webkit-flex;display:-ms-flexbox;display:flex;margin-bottom:' + _branding.space.l + ';}.kirk-tripCard.jsx-2639181855 .kirk-tripCard-itinerary{-webkit-flex:1;-ms-flex:1;flex:1;}.kirk-tripCard-price.jsx-2639181855{color:' + _branding.color.primaryText + ';font-size:' + _branding.font.m.size + ';line-height:' + _branding.font.m.lineHeight + ';font-weight:' + _branding.fontWeight.medium + ';}.kirk-tripCard--highlighted.jsx-2639181855 .kirk-tripCard-price.jsx-2639181855{color:' + _branding.color.success + ';}.kirk-tripCard-bottom.jsx-2639181855{display:-webkit-box;display:-webkit-flex;display:-ms-flexbox;display:flex;-webkit-align-items:center;-webkit-box-align:center;-ms-flex-align:center;align-items:center;}.kirk-tripCard-driver.jsx-2639181855{display:-webkit-box;display:-webkit-flex;display:-ms-flexbox;display:flex;-webkit-align-items:center;-webkit-box-align:center;-ms-flex-align:center;align-items:center;-webkit-flex:1;-ms-flex:1;flex:1;color:' + _branding.color.primaryText + ';font-size:' + _branding.font.m.size + ';line-height:' + _branding.font.m.lineHeight + ';}.kirk-tripCard.jsx-2639181855 .kirk-tripCard-driver > div{margin-right:calc(' + _branding.space.xl + ' + 6px);}.kirk-tripCard.jsx-2639181855 .kirk-tripCard-flags svg{display:inline-block;margin-left:' + _branding.space.m + ';}.kirk-tripCard-topText.jsx-2639181855{color:' + _branding.color.success + ';font-weight:' + _branding.fontWeight.medium + ';}';
_defaultExport.__scopedHash = '2639181855';
exports.default = _defaultExport;
//# sourceMappingURL=style.js.map