'use strict';

Object.defineProperty(exports, "__esModule", {
  value: true
});

var _branding = require('../_utils/branding');

var _defaultExport = new String('.kirk-checkbox{padding:' + _branding.space.l + ' 0;font-size:' + _branding.font.m.size + ';line-height:' + _branding.font.m.lineHeight + ';display:-webkit-box;display:-webkit-flex;display:-ms-flexbox;display:flex;-webkit-align-items:center;-webkit-box-align:center;-ms-flex-align:center;align-items:center;-webkit-box-pack:justify;-webkit-justify-content:space-between;-ms-flex-pack:justify;justify-content:space-between;position:relative;color:' + _branding.color.primaryText + ';cursor:pointer;}.kirk-checkbox div{display:-webkit-box;display:-webkit-flex;display:-ms-flexbox;display:flex;-webkit-flex-direction:column;-ms-flex-direction:column;flex-direction:column;}.kirk-checkbox div:first-child{padding-left:' + _branding.space.l + ';-webkit-order:2;-ms-flex-order:2;order:2;}.kirk-subLabel{color:' + _branding.color.secondaryText + ';font-size:' + _branding.font.base.size + ';display:block;line-height:' + _branding.font.base.lineHeight + ';}input{position:absolute;display:inline-block;width:1em;height:1em;margin:0;padding:0;opacity:0;}input+span{box-sizing:border-box;position:relative;display:inline-block;width:24px;height:24px;border-radius:24px;-webkit-transition-duration:' + _branding.transition.duration.base + ';transition-duration:' + _branding.transition.duration.base + ';border:1px solid ' + _branding.color.primary + ';background-color:' + _branding.color.white + ';}input+.checked{background-color:' + _branding.color.primary + ';}input+.checked::after{content:"";display:block;position:absolute;width:10px;height:6px;top:6px;left:6px;border-left:2px solid ' + _branding.color.white + ';border-bottom:2px solid ' + _branding.color.white + ';-webkit-transform:rotate(-45deg);-ms-transform:rotate(-45deg);transform:rotate(-45deg);}');

_defaultExport.__hash = '1161758871';
_defaultExport.__scoped = '.kirk-checkbox.jsx-3617985686{padding:' + _branding.space.l + ' 0;font-size:' + _branding.font.m.size + ';line-height:' + _branding.font.m.lineHeight + ';display:-webkit-box;display:-webkit-flex;display:-ms-flexbox;display:flex;-webkit-align-items:center;-webkit-box-align:center;-ms-flex-align:center;align-items:center;-webkit-box-pack:justify;-webkit-justify-content:space-between;-ms-flex-pack:justify;justify-content:space-between;position:relative;color:' + _branding.color.primaryText + ';cursor:pointer;}.kirk-checkbox.jsx-3617985686 div.jsx-3617985686{display:-webkit-box;display:-webkit-flex;display:-ms-flexbox;display:flex;-webkit-flex-direction:column;-ms-flex-direction:column;flex-direction:column;}.kirk-checkbox.jsx-3617985686 div.jsx-3617985686:first-child{padding-left:' + _branding.space.l + ';-webkit-order:2;-ms-flex-order:2;order:2;}.kirk-subLabel.jsx-3617985686{color:' + _branding.color.secondaryText + ';font-size:' + _branding.font.base.size + ';display:block;line-height:' + _branding.font.base.lineHeight + ';}input.jsx-3617985686{position:absolute;display:inline-block;width:1em;height:1em;margin:0;padding:0;opacity:0;}input.jsx-3617985686+span.jsx-3617985686{box-sizing:border-box;position:relative;display:inline-block;width:24px;height:24px;border-radius:24px;-webkit-transition-duration:' + _branding.transition.duration.base + ';transition-duration:' + _branding.transition.duration.base + ';border:1px solid ' + _branding.color.primary + ';background-color:' + _branding.color.white + ';}input.jsx-3617985686+.checked.jsx-3617985686{background-color:' + _branding.color.primary + ';}input.jsx-3617985686+.checked.jsx-3617985686::after{content:"";display:block;position:absolute;width:10px;height:6px;top:6px;left:6px;border-left:2px solid ' + _branding.color.white + ';border-bottom:2px solid ' + _branding.color.white + ';-webkit-transform:rotate(-45deg);-ms-transform:rotate(-45deg);transform:rotate(-45deg);}';
_defaultExport.__scopedHash = '3617985686';
exports.default = _defaultExport;
//# sourceMappingURL=style.js.map