'use strict';

Object.defineProperty(exports, "__esModule", {
  value: true
});

var _branding = require('../_utils/branding');

var _defaultExport = new String('.kirk-timePicker{position:relative;display:-webkit-inline-box;display:-webkit-inline-flex;display:-ms-inline-flexbox;display:inline-flex;-webkit-box-pack:center;-webkit-justify-content:center;-ms-flex-pack:center;justify-content:center;-webkit-align-items:center;-webkit-box-align:center;-ms-flex-align:center;align-items:center;width:320px;max-width:100%;font-size:82px;font-weight:500;line-height:1;background-color:' + _branding.color.white + ';color:' + _branding.color.primaryText + ';border:1px solid ' + _branding.color.border + ';border-radius:66px;box-sizing:border-box;cursor:pointer;}.kirk-timePicker:hover{background-color:' + _branding.color.lightBackground + ';}.kirk-timePicker::after{content :\'\';position:absolute;right:32px;top:calc(50% - 8px);display:inline-block;padding:5px;border:solid ' + _branding.color.primary + ';border-width:0 2px 2px 0;vertical-align:middle;-webkit-transform:rotate(45deg);-ms-transform:rotate(45deg);transform:rotate(45deg);}.kirk-timePicker[aria-disabled="true"]{color:' + _branding.color.disabled + ';border-color:transparent;}.kirk-timePicker[aria-disabled="true"]::after{border-color:' + _branding.color.disabled + ';}.kirk-timePicker>select{position:absolute;top:0;left:0;width:100%;height:100%;opacity:0;font-size:' + _branding.font.base.size + ';-webkit-appearance:menulist-button;cursor:pointer;}.kirk-timePicker>time{display:inline-block;padding-top:6px;vertical-align:middle;}');

_defaultExport.__hash = '4053232946';
_defaultExport.__scoped = '.kirk-timePicker.jsx-3648182387{position:relative;display:-webkit-inline-box;display:-webkit-inline-flex;display:-ms-inline-flexbox;display:inline-flex;-webkit-box-pack:center;-webkit-justify-content:center;-ms-flex-pack:center;justify-content:center;-webkit-align-items:center;-webkit-box-align:center;-ms-flex-align:center;align-items:center;width:320px;max-width:100%;font-size:82px;font-weight:500;line-height:1;background-color:' + _branding.color.white + ';color:' + _branding.color.primaryText + ';border:1px solid ' + _branding.color.border + ';border-radius:66px;box-sizing:border-box;cursor:pointer;}.kirk-timePicker.jsx-3648182387:hover{background-color:' + _branding.color.lightBackground + ';}.kirk-timePicker.jsx-3648182387::after{content :\'\';position:absolute;right:32px;top:calc(50% - 8px);display:inline-block;padding:5px;border:solid ' + _branding.color.primary + ';border-width:0 2px 2px 0;vertical-align:middle;-webkit-transform:rotate(45deg);-ms-transform:rotate(45deg);transform:rotate(45deg);}.kirk-timePicker[aria-disabled="true"].jsx-3648182387{color:' + _branding.color.disabled + ';border-color:transparent;}.kirk-timePicker[aria-disabled="true"].jsx-3648182387::after{border-color:' + _branding.color.disabled + ';}.kirk-timePicker.jsx-3648182387>select.jsx-3648182387{position:absolute;top:0;left:0;width:100%;height:100%;opacity:0;font-size:' + _branding.font.base.size + ';-webkit-appearance:menulist-button;cursor:pointer;}.kirk-timePicker.jsx-3648182387>time.jsx-3648182387{display:inline-block;padding-top:6px;vertical-align:middle;}';
_defaultExport.__scopedHash = '3648182387';
exports.default = _defaultExport;
//# sourceMappingURL=style.js.map