'use strict';

Object.defineProperty(exports, "__esModule", {
  value: true
});

var _branding = require('../_utils/branding');

var _defaultExport = new String('button{position:relative;min-width:40px;height:48px;border:0;background:transparent;color:' + _branding.color.primary + ';outline:0;cursor:pointer;-webkit-user-select:none;-moz-user-select:none;-ms-user-select:none;user-select:none;}i{display:block;margin:0 auto;width:20px;height:2px;background-color:currentColor;-webkit-transition:background-color 50ms linear;transition:background-color 50ms linear;-webkit-transition-delay:50ms;transition-delay:50ms;pointer-events:none;}i::before,i::after{content:\'\';display:block;position:absolute;width:inherit;height:inherit;border-radius:inherit;background-color:currentColor;-webkit-transition:-webkit-transform 100ms linear;-webkit-transition:transform 100ms linear;transition:transform 100ms linear;z-index:inherit;}i::before{-webkit-transform:translateY(-6px);-ms-transform:translateY(-6px);transform:translateY(-6px);}i::after{-webkit-transform:translateY(6px);-ms-transform:translateY(6px);transform:translateY(6px);}button[aria-expanded="true"] i{background-color:transparent;-webkit-transition-delay:unset;transition-delay:unset;}button[aria-expanded="true"] i::before{-webkit-transform:translateY(0) rotate(135deg);-ms-transform:translateY(0) rotate(135deg);transform:translateY(0) rotate(135deg);}button[aria-expanded="true"] i::after{-webkit-transform:translateY(0) rotate(45deg);-ms-transform:translateY(0) rotate(45deg);transform:translateY(0) rotate(45deg);}');

_defaultExport.__hash = '4191597672';
_defaultExport.__scoped = 'button.jsx-1400275785{position:relative;min-width:40px;height:48px;border:0;background:transparent;color:' + _branding.color.primary + ';outline:0;cursor:pointer;-webkit-user-select:none;-moz-user-select:none;-ms-user-select:none;user-select:none;}i.jsx-1400275785{display:block;margin:0 auto;width:20px;height:2px;background-color:currentColor;-webkit-transition:background-color 50ms linear;transition:background-color 50ms linear;-webkit-transition-delay:50ms;transition-delay:50ms;pointer-events:none;}i.jsx-1400275785::before,i.jsx-1400275785::after{content:\'\';display:block;position:absolute;width:inherit;height:inherit;border-radius:inherit;background-color:currentColor;-webkit-transition:-webkit-transform 100ms linear;-webkit-transition:transform 100ms linear;transition:transform 100ms linear;z-index:inherit;}i.jsx-1400275785::before{-webkit-transform:translateY(-6px);-ms-transform:translateY(-6px);transform:translateY(-6px);}i.jsx-1400275785::after{-webkit-transform:translateY(6px);-ms-transform:translateY(6px);transform:translateY(6px);}button[aria-expanded="true"].jsx-1400275785 i.jsx-1400275785{background-color:transparent;-webkit-transition-delay:unset;transition-delay:unset;}button[aria-expanded="true"].jsx-1400275785 i.jsx-1400275785::before{-webkit-transform:translateY(0) rotate(135deg);-ms-transform:translateY(0) rotate(135deg);transform:translateY(0) rotate(135deg);}button[aria-expanded="true"].jsx-1400275785 i.jsx-1400275785::after{-webkit-transform:translateY(0) rotate(45deg);-ms-transform:translateY(0) rotate(45deg);transform:translateY(0) rotate(45deg);}';
_defaultExport.__scopedHash = '1400275785';
exports.default = _defaultExport;
//# sourceMappingURL=style.js.map