'use strict';

Object.defineProperty(exports, "__esModule", {
  value: true
});

var _branding = require('../_utils/branding');

/* Kirk overrides */
var _defaultExport = new String('.datePicker{height:100%;}.DayPicker__horizontal,.DayPicker__verticalScrollable{box-shadow:none;}.DayPickerNavigation_button{background:none;border:0;border-radius:50%;width:48px;height:48px;-webkit-tap-highlight-color:' + _branding.color.tapHighlight + ';}.DayPickerNavigation_button:hover{background-color:' + _branding.color.lightBackground + ';}@media (hover:none),(hover:on-demand){.DayPickerNavigation_button:hover{background-color:transparent;}}.DayPicker_weekHeader{color:' + _branding.color.primaryText + ';}.DayPicker_weekHeader small{font-size:' + _branding.font.base.size + ';}.DayPicker_weekHeader_ul{display:-webkit-box;display:-webkit-flex;display:-ms-flexbox;display:flex;-webkit-align-items:center;-webkit-box-align:center;-ms-flex-align:center;align-items:center;height:48px;}.CalendarMonth_caption{padding-top:28px;padding-bottom:58px;color:' + _branding.color.primaryText + ';font-size:' + _branding.font.l.size + ';font-weight:normal;}.CalendarMonth_caption::first-letter{text-transform:uppercase;}.CalendarMonth_caption strong{font-weight:normal;}.CalendarDay__default,.CalendarDay__default:hover{font:inherit;border-color:transparent;color:' + _branding.color.secondaryText + ';background:none;cursor:pointer;-webkit-tap-highlight-color:rgba(0,0,0,0);}.CalendarDay__blocked_out_of_range,.CalendarDay__blocked_out_of_range:active,.CalendarDay__blocked_out_of_range:hover{color:' + _branding.color.disabled + ';}.CalendarDay__button{display:-webkit-box;display:-webkit-flex;display:-ms-flexbox;display:flex;-webkit-align-items:center;-webkit-box-align:center;-ms-flex-align:center;align-items:center;-webkit-box-pack:center;-webkit-justify-content:center;-ms-flex-pack:center;justify-content:center;margin:0 auto;border-radius:50%;width:36px;height:36px;}.CalendarDay__default :not(.CalendarDay__blocked_out_of_range) :not(.CalendarDay__selected)  .CalendarDay__button:hover{background-color:' + _branding.color.lightBackground + ';}.CalendarDay__selected .CalendarDay__button{background-color:' + _branding.color.primary + ';color:' + _branding.color.white + ';}.DayPicker_transitionContainer__verticalScrollable{padding-top:30px;-webkit-overflow-scrolling:touch;}.CalendarMonth_caption__verticalScrollable{padding-top:30px;padding-bottom:7px;}.CalendarMonthGrid__vertical_scrollable{margin:0;}.DayPicker__verticalScrollable .CalendarMonth{padding:0;}.DayPicker__verticalScrollable .CalendarMonth_caption{padding-left:12px;padding-bottom:16px;text-align:left;}.DayPicker_weekHeader__verticalScrollable{padding:0;border:0;}.DayPicker__verticalScrollable .DayPicker_weekHeader_li{font-size:' + _branding.font.base.size + ';padding:0;}');

_defaultExport.__hash = '3420349823';
_defaultExport.__scoped = '.datePicker{height:100%;}.DayPicker__horizontal,.DayPicker__verticalScrollable{box-shadow:none;}.DayPickerNavigation_button{background:none;border:0;border-radius:50%;width:48px;height:48px;-webkit-tap-highlight-color:' + _branding.color.tapHighlight + ';}.DayPickerNavigation_button:hover{background-color:' + _branding.color.lightBackground + ';}@media (hover:none),(hover:on-demand){.DayPickerNavigation_button:hover{background-color:transparent;}}.DayPicker_weekHeader{color:' + _branding.color.primaryText + ';}.DayPicker_weekHeader small{font-size:' + _branding.font.base.size + ';}.DayPicker_weekHeader_ul{display:-webkit-box;display:-webkit-flex;display:-ms-flexbox;display:flex;-webkit-align-items:center;-webkit-box-align:center;-ms-flex-align:center;align-items:center;height:48px;}.CalendarMonth_caption{padding-top:28px;padding-bottom:58px;color:' + _branding.color.primaryText + ';font-size:' + _branding.font.l.size + ';font-weight:normal;}.CalendarMonth_caption::first-letter{text-transform:uppercase;}.CalendarMonth_caption strong{font-weight:normal;}.CalendarDay__default,.CalendarDay__default:hover{font:inherit;border-color:transparent;color:' + _branding.color.secondaryText + ';background:none;cursor:pointer;-webkit-tap-highlight-color:rgba(0,0,0,0);}.CalendarDay__blocked_out_of_range,.CalendarDay__blocked_out_of_range:active,.CalendarDay__blocked_out_of_range:hover{color:' + _branding.color.disabled + ';}.CalendarDay__button{display:-webkit-box;display:-webkit-flex;display:-ms-flexbox;display:flex;-webkit-align-items:center;-webkit-box-align:center;-ms-flex-align:center;align-items:center;-webkit-box-pack:center;-webkit-justify-content:center;-ms-flex-pack:center;justify-content:center;margin:0 auto;border-radius:50%;width:36px;height:36px;}.CalendarDay__default :not(.CalendarDay__blocked_out_of_range) :not(.CalendarDay__selected)  .CalendarDay__button:hover{background-color:' + _branding.color.lightBackground + ';}.CalendarDay__selected .CalendarDay__button{background-color:' + _branding.color.primary + ';color:' + _branding.color.white + ';}.DayPicker_transitionContainer__verticalScrollable{padding-top:30px;-webkit-overflow-scrolling:touch;}.CalendarMonth_caption__verticalScrollable{padding-top:30px;padding-bottom:7px;}.CalendarMonthGrid__vertical_scrollable{margin:0;}.DayPicker__verticalScrollable .CalendarMonth{padding:0;}.DayPicker__verticalScrollable .CalendarMonth_caption{padding-left:12px;padding-bottom:16px;text-align:left;}.DayPicker_weekHeader__verticalScrollable{padding:0;border:0;}.DayPicker__verticalScrollable .DayPicker_weekHeader_li{font-size:' + _branding.font.base.size + ';padding:0;}';
_defaultExport.__scopedHash = '3340948030';
exports.default = _defaultExport;
//# sourceMappingURL=theme.js.map